defaults:
  - _self_
  - override hydra/launcher: clusterduck_slurm
  - db: mysql


hydra:
  launcher:
    num_of_overrides_per_job: 4
    parallel_executions_in_job: 2
    exclusive_gpu_per_execution: False
