defaults:
  - db: mysql
  - _self_


hydra:
  launcher:
    num_of_overrides_per_job: 4
    parallel_executions_in_job: 2
    exclusive_gpu_per_execution: False
    gpus_per_node: 1
  job:
    env_set:
      CUDA_VISIBLE_DEVICES: "0"